"""
ALL_TRAILS API Module

This module provides API endpoints and utilities for the ALL_TRAILS application.
"""

import frappe
from frappe import _
from frappe.utils.response import build_response


@frappe.whitelist(allow_guest=True)
def get_frontend():
	"""
	Serve the ALL_TRAILS frontend application.
	
	This endpoint serves the built Vue 3 frontend application.
	It returns the index.html file with the necessary assets.
	"""
	try:
		# Read the built index.html file
		import os
		from pathlib import Path
		
		app_dir = Path(__file__).parent
		frontend_dir = app_dir / "public" / "frontend"
		index_file = frontend_dir / "index.html"
		
		if not index_file.exists():
			frappe.throw(_("Frontend not built. Please run 'bench migrate' to build the frontend."))
		
		with open(index_file, 'r') as f:
			html_content = f.read()
		
		# Return the HTML content
		frappe.response['message'] = html_content
		frappe.response['type'] = 'html'
		
	except Exception as e:
		frappe.logger().error(f"Error serving frontend: {e}")
		frappe.throw(_("Error loading frontend application"))


@frappe.whitelist(allow_guest=True)
def get_frontend_assets():
	"""
	Get frontend asset hashes from Vite manifest.json
	Returns the correct script and CSS file names for dynamic loading

	Returns:
		dict: Asset file names with hashes
	"""
	try:
		import json
		import os

		# Path to manifest.json generated by Vite
		manifest_path = os.path.join(
			os.path.dirname(__file__),
			'public',
			'frontend',
			'.vite',
			'manifest.json'
		)

		# Fallback: check if manifest exists in the root of public/frontend
		if not os.path.exists(manifest_path):
			manifest_path = os.path.join(
				os.path.dirname(__file__),
				'public',
				'frontend',
				'manifest.json'
			)

		# If manifest doesn't exist, return empty (will use fallback in HTML)
		if not os.path.exists(manifest_path):
			return {
				"success": False,
				"message": "Manifest not found - using fallback",
				"js_file": None,
				"css_file": None
			}

		with open(manifest_path, 'r') as f:
			manifest = json.load(f)

		# Extract entry point (Vite uses index.html or src/main.ts)
		js_file = None
		css_file = None

		# Try different entry point names
		entry_names = ['index.html', 'src/main.ts', 'main.ts', 'src/main.jsx', 'main.jsx']

		for entry_name in entry_names:
			if entry_name in manifest:
				entry = manifest[entry_name]
				if 'file' in entry:
					js_file = entry['file']
				if 'css' in entry and len(entry['css']) > 0:
					css_file = entry['css'][0]
				break

		return {
			"success": True,
			"js_file": js_file,
			"css_file": css_file,
			"base_path": "/assets/all_trails/frontend/"
		}

	except Exception as e:
		frappe.logger().error(f"Error reading frontend manifest: {str(e)}")
		return {
			"success": False,
			"message": str(e),
			"js_file": None,
			"css_file": None
		}


@frappe.whitelist(allow_guest=True)
def get_social_login_providers():
	"""
	Get available social login providers for the login page.
	
	Returns:
		dict: List of social login providers with their auth URLs
	"""
	try:
		from frappe.utils.oauth import get_oauth2_authorize_url, get_oauth_keys
		from frappe.utils.password import get_decrypted_password
		from frappe.utils.html_utils import get_icon_html
		from frappe.utils.data import escape_html
		
		providers = frappe.get_all(
			"Social Login Key",
			filters={"enable_social_login": 1},
			fields=["name", "client_id", "base_url", "provider_name", "icon"],
			order_by="name",
		)
		
		provider_logins = []
		
		for provider in providers:
			client_secret = get_decrypted_password(
				"Social Login Key", provider.name, "client_secret", raise_exception=False
			)
			if not client_secret:
				continue
			
			icon = None
			if provider.icon:
				if provider.provider_name == "Custom":
					icon = get_icon_html(provider.icon, small=True)
				else:
					icon = escape_html(provider.icon)
			
			if provider.client_id and provider.base_url and get_oauth_keys(provider.name):
				redirect_to = frappe.local.request.args.get("redirect-to") or "/all-trails/"
				provider_logins.append({
					"name": provider.name,
					"provider_name": provider.provider_name,
					"auth_url": get_oauth2_authorize_url(provider.name, redirect_to),
					"icon": icon,
				})
		
		return {
			"success": True,
			"providers": provider_logins
		}
	except Exception as e:
		frappe.logger().error(f"Error getting social login providers: {e}")
		return {
			"success": False,
			"providers": []
		}

