import type {
  CouponValidationResult,
  MerchandiseCategory,
  MerchandiseItem,
  MerchandiseReview,
} from '../types/shop'

const buildImage = (title: string, accentA: string, accentB: string) =>
  `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900" viewBox="0 0 1200 900">
      <defs>
        <linearGradient id="g" x1="0%" x2="100%" y1="0%" y2="100%">
          <stop offset="0%" stop-color="${accentA}" />
          <stop offset="100%" stop-color="${accentB}" />
        </linearGradient>
      </defs>
      <rect width="1200" height="900" fill="url(#g)" />
      <circle cx="220" cy="180" r="170" fill="rgba(255,255,255,0.13)" />
      <circle cx="980" cy="760" r="200" fill="rgba(255,255,255,0.12)" />
      <rect x="120" y="120" width="960" height="660" rx="52" fill="rgba(13,23,18,0.16)" stroke="rgba(255,255,255,0.24)" />
      <text x="120" y="360" font-family="Sora, sans-serif" font-size="96" font-weight="700" fill="#ffffff">${title}</text>
      <text x="120" y="450" font-family="Inter, sans-serif" font-size="36" fill="rgba(255,255,255,0.82)">Stepup Adventures Shop</text>
    </svg>
  `)}`

export const mockMerchandiseCategories: MerchandiseCategory[] = [
  {
    name: 'Packs',
    slug: 'packs',
    description: 'Fast-day packs and multi-day carry systems built for East African terrain.',
    hero_copy: 'Carry less dead weight and more altitude.',
    accent: '#5b7f72',
    image_url: buildImage('Packs', '#345247', '#8aa99a'),
    featured: true,
    sort_order: 1,
  },
  {
    name: 'Apparel',
    slug: 'apparel',
    description: 'Layering pieces tuned for early starts, summit wind, and post-hike coffee.',
    hero_copy: 'Warm when the ridge opens up.',
    accent: '#925d40',
    image_url: buildImage('Apparel', '#6f4336', '#c89a7a'),
    featured: true,
    sort_order: 2,
  },
  {
    name: 'Camp Kitchen',
    slug: 'camp-kitchen',
    description: 'Drinkware and camp essentials that survive the boot of the shuttle van.',
    hero_copy: 'Ritual gear for the trailhead and the fireline.',
    accent: '#657a88',
    image_url: buildImage('Camp Kitchen', '#4c6575', '#92adbb'),
    featured: false,
    sort_order: 3,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Small-format performance gear that solves the annoying parts of hiking.',
    hero_copy: 'Tiny upgrades, big comfort.',
    accent: '#8f6a3e',
    image_url: buildImage('Accessories', '#6d4e2b', '#c7a06c'),
    featured: false,
    sort_order: 4,
  },
]

export const mockMerchandiseItems: MerchandiseItem[] = [
  {
    item_code: 'SUMMIT-PACK-28',
    slug: 'summit-pack-28',
    item_name: 'Summit Pack 28L',
    category_slug: 'packs',
    category_name: 'Packs',
    short_description: 'An all-day technical pack with hydration routing and weatherproof shell.',
    description:
      'Built for fast ascents and late descents, the Summit Pack 28L balances stable carry, quick-access organization, and enough structure for camera gear, layers, and food. It is the day-pack we would issue to every first-time Mount Longonot convert.',
    selling_price: 12400,
    discount_price: 10800,
    average_rating: 4.8,
    review_count: 34,
    image_url: buildImage('Summit Pack', '#3f6557', '#91ab9d'),
    gallery_urls: [
      buildImage('Pack Front', '#3f6557', '#91ab9d'),
      buildImage('Pack Profile', '#2e433a', '#6f8f84'),
      buildImage('Pack Trail', '#48655a', '#b9d0c3'),
    ],
    highlights: ['28L weatherproof shell', 'Ventilated back panel', 'Quick-stash trekking pole loops'],
    materials: ['420D recycled ripstop', 'YKK AquaGuard zips', 'Closed-cell foam frame sheet'],
    badges: ['Best Seller', 'BNPL Ready'],
    inventory_qty: 17,
    available_colors: ['Mist Olive', 'Basalt Black', 'Clay Dune'],
    available_sizes: ['One Size'],
    estimated_dispatch: 'Ships in 24 hours',
    is_featured: true,
    is_active: true,
    bnpl_eligible: true,
    bnpl_min_amount: 9000,
    featured_copy: 'The core carry piece for guided day hikes and quick overnighters.',
  },
  {
    item_code: 'RIDGELINE-SHELL',
    slug: 'ridgeline-shell',
    item_name: 'Ridgeline Shell Jacket',
    category_slug: 'apparel',
    category_name: 'Apparel',
    short_description: 'A lightweight shell with enough structure for sudden escarpment wind.',
    description:
      'The Ridgeline Shell is our answer to volatile shoulder-season forecasts. It packs down small, cuts rain on the move, and keeps the fit trim enough to work over base layers without flapping on exposed sections.',
    selling_price: 14900,
    discount_price: 13250,
    average_rating: 4.7,
    review_count: 21,
    image_url: buildImage('Ridgeline Shell', '#6f4336', '#c89a7a'),
    gallery_urls: [
      buildImage('Shell Front', '#6f4336', '#c89a7a'),
      buildImage('Shell Detail', '#5a3128', '#b77f63'),
    ],
    highlights: ['10K waterproof membrane', 'Helmet-compatible hood', 'Two-way venting zips'],
    materials: ['3-layer laminate', 'Taped seams', 'Recycled nylon face'],
    badges: ['Limited Run'],
    inventory_qty: 12,
    available_colors: ['Summit Rust', 'Night Pine'],
    available_sizes: ['S', 'M', 'L', 'XL'],
    estimated_dispatch: 'Ships in 48 hours',
    is_featured: true,
    is_active: true,
    bnpl_eligible: true,
    bnpl_min_amount: 12000,
    featured_copy: 'A high-comfort weather layer for cold starts and ridge gusts.',
  },
  {
    item_code: 'ALPINE-FLASK-1L',
    slug: 'alpine-flask-1l',
    item_name: 'Alpine Flask 1L',
    category_slug: 'camp-kitchen',
    category_name: 'Camp Kitchen',
    short_description: 'Double-wall bottle for cold summit water or hot chai on the return leg.',
    description:
      'Vacuum insulated, easy to clean, and fitted with a grippy powder coat that does not turn slick once the altitude sweat kicks in.',
    selling_price: 3600,
    discount_price: 3200,
    average_rating: 4.9,
    review_count: 58,
    image_url: buildImage('Alpine Flask', '#4c6575', '#92adbb'),
    gallery_urls: [
      buildImage('Flask Front', '#4c6575', '#92adbb'),
      buildImage('Flask Detail', '#38505e', '#7f9eac'),
    ],
    highlights: ['24-hour cold retention', '18/8 stainless build', 'Leak-lock loop cap'],
    materials: ['Stainless steel', 'BPA-free lid gasket'],
    badges: ['Gift Pick'],
    inventory_qty: 46,
    available_colors: ['Glacier Blue', 'Trail Sand', 'Forest'],
    available_sizes: ['1L'],
    estimated_dispatch: 'Ships today',
    is_featured: true,
    is_active: true,
    bnpl_eligible: false,
    bnpl_min_amount: 5000,
    featured_copy: 'A practical daily-carry piece with premium finish.',
  },
  {
    item_code: 'TRAIL-LAMP-X2',
    slug: 'trail-lamp-x2',
    item_name: 'Trail Lamp X2',
    category_slug: 'accessories',
    category_name: 'Accessories',
    short_description: 'Rechargeable headlamp with a broad beam for pre-dawn trail starts.',
    description:
      'Balanced front weight, glove-friendly controls, and enough throw to make rocky descent lines obvious before the sun catches up.',
    selling_price: 5400,
    discount_price: null,
    average_rating: 4.6,
    review_count: 18,
    image_url: buildImage('Trail Lamp', '#6d4e2b', '#c7a06c'),
    gallery_urls: [
      buildImage('Lamp Front', '#6d4e2b', '#c7a06c'),
      buildImage('Lamp Strap', '#5d4324', '#a67d4c'),
    ],
    highlights: ['450-lumen flood beam', 'USB-C rechargeable', 'Red-light camp mode'],
    materials: ['Impact-resistant polymer', 'Elastic comfort strap'],
    badges: ['Guide Pick'],
    inventory_qty: 28,
    available_colors: ['Rock', 'Sand'],
    available_sizes: ['One Size'],
    estimated_dispatch: 'Ships today',
    is_featured: false,
    is_active: true,
    bnpl_eligible: false,
    bnpl_min_amount: 5000,
  },
  {
    item_code: 'CAMP-MUG-SET',
    slug: 'camp-mug-set',
    item_name: 'Camp Mug Duo',
    category_slug: 'camp-kitchen',
    category_name: 'Camp Kitchen',
    short_description: 'Two enamel-look insulated mugs sized for campsite brews.',
    description:
      'A compact giftable set that makes the last thirty minutes of the hike feel like the beginning of the evening.',
    selling_price: 2900,
    discount_price: 2400,
    average_rating: 4.5,
    review_count: 16,
    image_url: buildImage('Camp Mug Duo', '#56716f', '#9dbab6'),
    gallery_urls: [
      buildImage('Mug Set', '#56716f', '#9dbab6'),
      buildImage('Mug Detail', '#4a6261', '#85a39f'),
    ],
    highlights: ['Set of two', 'Splash-resistant lids', 'Stackable profile'],
    materials: ['Powder-coated steel', 'Sip-through lids'],
    badges: ['Camp Favorite'],
    inventory_qty: 32,
    available_colors: ['Fog White', 'Ash Green'],
    available_sizes: ['350ml'],
    estimated_dispatch: 'Ships today',
    is_featured: false,
    is_active: true,
    bnpl_eligible: false,
    bnpl_min_amount: 5000,
  },
  {
    item_code: 'HORIZON-HOODIE',
    slug: 'horizon-hoodie',
    item_name: 'Horizon Merino Hoodie',
    category_slug: 'apparel',
    category_name: 'Apparel',
    short_description: 'A breathable layering hoodie for cold trailheads and long-drive recoveries.',
    description:
      'Cut with a relaxed athletic drape, the Horizon Hoodie keeps warmth close without feeling bulky. It is the layer you want once everyone stops moving and the wind starts to count.',
    selling_price: 9800,
    discount_price: 8600,
    average_rating: 4.7,
    review_count: 25,
    image_url: buildImage('Horizon Hoodie', '#6b5a40', '#d0b386'),
    gallery_urls: [
      buildImage('Hoodie Front', '#6b5a40', '#d0b386'),
      buildImage('Hoodie Detail', '#59452e', '#ab8a57'),
    ],
    highlights: ['Merino blend warmth', 'Thumb-loop cuff detail', 'Trail-to-town silhouette'],
    materials: ['Merino wool blend', 'Brushed inner face'],
    badges: ['New'],
    inventory_qty: 15,
    available_colors: ['Copper Ridge', 'Slate', 'Sage'],
    available_sizes: ['S', 'M', 'L', 'XL'],
    estimated_dispatch: 'Ships in 24 hours',
    is_featured: true,
    is_active: true,
    bnpl_eligible: true,
    bnpl_min_amount: 9000,
  },
  {
    item_code: 'RIFT-TREK-POLES',
    slug: 'rift-trek-poles',
    item_name: 'Rift Trek Poles',
    category_slug: 'accessories',
    category_name: 'Accessories',
    short_description: 'Adjustable carbon-composite trekking poles for steep and loose sections.',
    description:
      'These poles collapse small enough to lash onto a pack yet stay rigid when the route gets slippery. Strong tip bite, low weight, good wrist straps.',
    selling_price: 11800,
    discount_price: 10100,
    average_rating: 4.8,
    review_count: 29,
    image_url: buildImage('Trek Poles', '#5b655a', '#aab6a8'),
    gallery_urls: [
      buildImage('Poles Side', '#5b655a', '#aab6a8'),
      buildImage('Pole Grip', '#4c544b', '#8d9b89'),
    ],
    highlights: ['Carbon-composite shafts', 'Quick-lock height adjustment', 'Packed length under 40cm'],
    materials: ['Carbon-composite', 'Cork blend grip', 'Tungsten carbide tip'],
    badges: ['Guide Pick', 'BNPL Ready'],
    inventory_qty: 9,
    available_colors: ['Carbon', 'Sand'],
    available_sizes: ['One Size'],
    estimated_dispatch: 'Ships in 48 hours',
    is_featured: false,
    is_active: true,
    bnpl_eligible: true,
    bnpl_min_amount: 9000,
  },
]

export const mockReviewsByItem: Record<string, MerchandiseReview[]> = {
  'SUMMIT-PACK-28': [
    {
      id: 'r-pack-1',
      customer_name: 'Ruth M.',
      rating: 5,
      title: 'Stable even on fast descents',
      review_text:
        'It does not bounce around when packed properly, and the back ventilation made a real difference on a hot Ngong Hills loop.',
      created_at: '2026-02-14T09:30:00.000Z',
      verified_purchase: true,
      helpful_count: 11,
    },
    {
      id: 'r-pack-2',
      customer_name: 'Kevin O.',
      rating: 4,
      title: 'Premium feel',
      review_text:
        'Great hardware and stitching. I would take a second external pocket, but overall it feels like a major step up from generic packs.',
      created_at: '2026-01-22T14:05:00.000Z',
      verified_purchase: true,
      helpful_count: 5,
    },
  ],
  'RIDGELINE-SHELL': [
    {
      id: 'r-shell-1',
      customer_name: 'Angela W.',
      rating: 5,
      title: 'Saved a rainy Aberdare morning',
      review_text: 'Light enough to forget, solid enough once the weather turned. Hood fit is especially good.',
      created_at: '2026-02-02T07:45:00.000Z',
      verified_purchase: true,
      helpful_count: 8,
    },
  ],
  'ALPINE-FLASK-1L': [
    {
      id: 'r-flask-1',
      customer_name: 'Ian K.',
      rating: 5,
      title: 'Actually keeps water cold',
      review_text: 'Left it in the car after a hike and it still had ice. Easy recommendation.',
      created_at: '2026-03-04T11:20:00.000Z',
      verified_purchase: true,
      helpful_count: 4,
    },
  ],
}

export const mockCoupons: Record<string, CouponValidationResult> = {
  SUMMIT10: {
    valid: true,
    code: 'SUMMIT10',
    description: '10% off technical gear orders over KES 5,000',
    discount_type: 'percentage',
    discount_value: 10,
    max_discount: 1800,
    min_subtotal: 5000,
  },
  FREESHIP: {
    valid: true,
    code: 'FREESHIP',
    description: 'Waive standard shipping on this order',
    discount_type: 'shipping',
    discount_value: 650,
    min_subtotal: 3500,
  },
}
