import type { Trail, TrailBooking, User } from '../types/index';

// Mock Trails Data
export const mockTrails: Trail[] = [
  {
    id: 'trail-001',
    title: 'Mount Kenya Summit Trek',
    description: 'A challenging 3-day trek to the summit of Mount Kenya, Africa\'s second-highest peak.',
    difficulty_level: 'Hard',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.1536, lng: 37.2744 },
    distance_km: 45,
    elevation_gain_m: 2500,
    duration_hours: 48,
    scheduled_date: '2025-01-15',
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 12,
    available_spots: 5,
    price_kshs: 15000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/mount-kenya.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-002',
    title: 'Hell\'s Gate National Park Hike',
    description: 'A scenic day hike through Hell\'s Gate with geothermal features and wildlife viewing.',
    difficulty_level: 'Moderate',
    location: 'Naivasha, Kenya',
    coordinates: { lat: -0.8, lng: 36.3 },
    distance_km: 18,
    elevation_gain_m: 400,
    duration_hours: 6,
    scheduled_date: '2025-01-20',
    start_time: '07:00',
    end_time: '13:00',
    max_capacity: 20,
    available_spots: 12,
    price_kshs: 3500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/hells-gate.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-003',
    title: 'Aberdare Waterfall Trail',
    description: 'A gentle walk through the Aberdare forest to discover beautiful waterfalls.',
    difficulty_level: 'Easy',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.35, lng: 36.75 },
    distance_km: 8,
    elevation_gain_m: 200,
    duration_hours: 3,
    scheduled_date: '2025-01-25',
    start_time: '08:00',
    end_time: '11:00',
    max_capacity: 30,
    available_spots: 25,
    price_kshs: 1500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/aberdare.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-004',
    title: 'Kilimanjaro Expedition',
    description: 'A 6-day expedition to the summit of Mount Kilimanjaro, the highest peak in Africa.',
    difficulty_level: 'Expert',
    location: 'Moshi, Tanzania',
    coordinates: { lat: -3.0674, lng: 37.3556 },
    distance_km: 65,
    elevation_gain_m: 3800,
    duration_hours: 120,
    scheduled_date: '2025-02-01',
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 10,
    available_spots: 3,
    price_kshs: 45000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/kilimanjaro.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
];

// Mock User Bookings
export const mockBookings: TrailBooking[] = [
  {
    id: 'booking-001',
    user: 'user@example.com',
    trail_id: 'trail-001',
    booking_date: '2025-01-05T10:00:00Z',
    status: 'Confirmed',
    spots_booked: 2,
    total_price: 30000,
    payment_status: 'Completed',
    confirmation_code: 'CONF-001-ABC',
    created_at: '2025-01-05T10:00:00Z',
    updated_at: '2025-01-05T10:00:00Z',
  },
];

// Mock Current User
export const mockCurrentUser: User = {
  name: 'user@example.com',
  email: 'user@example.com',
  full_name: 'John Doe',
  user_image: '/assets/all_trails/images/user-avatar.jpg',
};

