import type { Trail, TrailBooking, User } from '../types/index';

// Helper function to get dates relative to today
const getDate = (daysFromToday: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromToday);
  const isoString = date.toISOString();
  return isoString.split('T')[0] || date.toISOString().substring(0, 10);
};

// Mock Trails Data - Spread across multiple dates for calendar view
export const mockTrails: Trail[] = [
  // Week 1 - Current Week
  {
    id: 'trail-001',
    title: 'Mount Kenya Summit Trek',
    description: 'A challenging 3-day trek to the summit of Mount Kenya, Africa\'s second-highest peak. Experience breathtaking views and alpine landscapes.',
    difficulty_level: 'Hard',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.1536, lng: 37.2744 },
    distance_km: 45,
    elevation_gain_m: 2500,
    duration_hours: 48,
    scheduled_date: getDate(2), // 2 days from today
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 12,
    available_spots: 5,
    price_kshs: 15000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/mount-kenya.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'camping-001',
        name: 'Camping Experience',
        description: 'Overnight camping at base camp with professional gear and guide',
        price_kshs: 5000,
        icon: '⛺',
        available: true,
        requires_booking: true,
        max_participants: 12,
        available_spots: 5
      }
    ],
    is_long_weekend: true,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-002',
    title: 'Karura Forest Morning Walk',
    description: 'A peaceful morning walk through Nairobi\'s Karura Forest. Perfect for beginners and families.',
    difficulty_level: 'Easy',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2345, lng: 36.7890 },
    distance_km: 5,
    elevation_gain_m: 50,
    duration_hours: 2,
    scheduled_date: getDate(2), // Same day as Mount Kenya
    start_time: '07:00',
    end_time: '09:00',
    max_capacity: 30,
    available_spots: 22,
    price_kshs: 800,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/karura.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-003',
    title: 'Ngong Hills Hike',
    description: 'Scenic hike through the iconic Ngong Hills with panoramic views of the Great Rift Valley.',
    difficulty_level: 'Moderate',
    location: 'Ngong, Kenya',
    coordinates: { lat: -1.3456, lng: 36.6543 },
    distance_km: 12,
    elevation_gain_m: 600,
    duration_hours: 4,
    scheduled_date: getDate(5), // 5 days from today
    start_time: '08:00',
    end_time: '12:00',
    max_capacity: 25,
    available_spots: 15,
    price_kshs: 2500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/ngong.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-004',
    title: 'Hell\'s Gate National Park Hike',
    description: 'A scenic day hike through Hell\'s Gate with geothermal features and wildlife viewing. Great for photography enthusiasts.',
    difficulty_level: 'Moderate',
    location: 'Naivasha, Kenya',
    coordinates: { lat: -0.8, lng: 36.3 },
    distance_km: 18,
    elevation_gain_m: 400,
    duration_hours: 6,
    scheduled_date: getDate(7), // 7 days from today
    start_time: '07:00',
    end_time: '13:00',
    max_capacity: 20,
    available_spots: 12,
    price_kshs: 3500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/hells-gate.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'golf-001',
        name: 'Golf Round',
        description: 'Play a round of golf at the nearby Great Rift Valley Golf Resort (18 holes)',
        price_kshs: 3500,
        icon: '⛳',
        available: true,
        requires_booking: true,
        max_participants: 4,
        available_spots: 2
      },
      {
        id: 'camping-002',
        name: 'Overnight Camping',
        description: 'Extend your adventure with overnight camping near the park',
        price_kshs: 2500,
        icon: '⛺',
        available: true,
        requires_booking: true,
        max_participants: 20,
        available_spots: 12
      }
    ],
    is_long_weekend: true,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-005',
    title: 'Aberdare Waterfall Trail',
    description: 'A gentle walk through the Aberdare forest to discover beautiful waterfalls. Perfect for nature lovers.',
    difficulty_level: 'Easy',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.35, lng: 36.75 },
    distance_km: 8,
    elevation_gain_m: 200,
    duration_hours: 3,
    scheduled_date: getDate(9), // 9 days from today
    start_time: '08:00',
    end_time: '11:00',
    max_capacity: 30,
    available_spots: 25,
    price_kshs: 1500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/aberdare.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-006',
    title: 'Longonot Crater Climb',
    description: 'Challenging climb to the rim of Mount Longonot crater. Stunning views of the Rift Valley await at the summit.',
    difficulty_level: 'Hard',
    location: 'Naivasha, Kenya',
    coordinates: { lat: -0.9153, lng: 36.4567 },
    distance_km: 13,
    elevation_gain_m: 900,
    duration_hours: 5,
    scheduled_date: getDate(10), // 10 days from today
    start_time: '06:30',
    end_time: '11:30',
    max_capacity: 15,
    available_spots: 8,
    price_kshs: 4000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/longonot.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'golf-002',
        name: 'Golf Experience',
        description: 'Enjoy a round of golf at the nearby Naivasha Golf Club after your hike',
        price_kshs: 3000,
        icon: '⛳',
        available: true,
        requires_booking: true,
        max_participants: 4,
        available_spots: 3
      }
    ],
    is_long_weekend: false,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-007',
    title: 'Oloolua Nature Trail',
    description: 'Easy nature walk through Oloolua Forest. Great for bird watching and family outings.',
    difficulty_level: 'Easy',
    location: 'Karen, Nairobi',
    coordinates: { lat: -1.3234, lng: 36.7123 },
    distance_km: 4,
    elevation_gain_m: 100,
    duration_hours: 2.5,
    scheduled_date: getDate(12), // 12 days from today
    start_time: '08:30',
    end_time: '11:00',
    max_capacity: 35,
    available_spots: 28,
    price_kshs: 1000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/oloolua.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-008',
    title: 'Menengai Crater Hike',
    description: 'Moderate hike around the Menengai Crater rim. One of the largest calderas in the world with fascinating geology.',
    difficulty_level: 'Moderate',
    location: 'Nakuru, Kenya',
    coordinates: { lat: -0.2, lng: 36.0667 },
    distance_km: 15,
    elevation_gain_m: 500,
    duration_hours: 5,
    scheduled_date: getDate(14), // 14 days from today
    start_time: '07:30',
    end_time: '12:30',
    max_capacity: 20,
    available_spots: 14,
    price_kshs: 3000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/menengai.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-009',
    title: 'Mount Elgon Trek',
    description: 'Multi-day trek to the summit of Mount Elgon. Experience diverse ecosystems from forest to alpine zones.',
    difficulty_level: 'Expert',
    location: 'Kitale, Kenya',
    coordinates: { lat: 1.1333, lng: 34.55 },
    distance_km: 60,
    elevation_gain_m: 3000,
    duration_hours: 72,
    scheduled_date: getDate(15), // 15 days from today
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 10,
    available_spots: 2,
    price_kshs: 25000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/elgon.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-010',
    title: 'Karura Waterfall Trail',
    description: 'Easy walk to the beautiful waterfall in Karura Forest. Perfect for a weekend family adventure.',
    difficulty_level: 'Easy',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2345, lng: 36.7890 },
    distance_km: 6,
    elevation_gain_m: 80,
    duration_hours: 2.5,
    scheduled_date: getDate(16), // 16 days from today
    start_time: '09:00',
    end_time: '11:30',
    max_capacity: 40,
    available_spots: 35,
    price_kshs: 1200,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/karura-waterfall.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-011',
    title: 'Chyulu Hills Adventure',
    description: 'Moderate to hard hike through the Chyulu Hills. Known for its unique volcanic landscape and wildlife.',
    difficulty_level: 'Hard',
    location: 'Makueni, Kenya',
    coordinates: { lat: -2.6833, lng: 37.8833 },
    distance_km: 22,
    elevation_gain_m: 1200,
    duration_hours: 8,
    scheduled_date: getDate(18), // 18 days from today
    start_time: '06:00',
    end_time: '14:00',
    max_capacity: 12,
    available_spots: 6,
    price_kshs: 5500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/chyulu.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-012',
    title: 'Sura Waterfall Hike',
    description: 'Moderate hike to Sura Waterfall in the Aberdare Range. Beautiful scenery and refreshing natural pool.',
    difficulty_level: 'Moderate',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.4, lng: 36.8 },
    distance_km: 10,
    elevation_gain_m: 350,
    duration_hours: 4,
    scheduled_date: getDate(19), // 19 days from today
    start_time: '08:00',
    end_time: '12:00',
    max_capacity: 25,
    available_spots: 18,
    price_kshs: 2800,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/sura.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-013',
    title: 'Kilimanjaro Expedition',
    description: 'A 6-day expedition to the summit of Mount Kilimanjaro, the highest peak in Africa. The ultimate hiking challenge.',
    difficulty_level: 'Expert',
    location: 'Moshi, Tanzania',
    coordinates: { lat: -3.0674, lng: 37.3556 },
    distance_km: 65,
    elevation_gain_m: 3800,
    duration_hours: 120,
    scheduled_date: getDate(21), // 21 days from today
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 10,
    available_spots: 3,
    price_kshs: 45000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/kilimanjaro.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-014',
    title: 'Nairobi Arboretum Walk',
    description: 'Easy stroll through Nairobi Arboretum. Perfect for beginners and those looking for a peaceful nature experience.',
    difficulty_level: 'Easy',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2674, lng: 36.7917 },
    distance_km: 3,
    elevation_gain_m: 30,
    duration_hours: 1.5,
    scheduled_date: getDate(21), // Same day as Kilimanjaro
    start_time: '10:00',
    end_time: '11:30',
    max_capacity: 50,
    available_spots: 45,
    price_kshs: 500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/arboretum.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-015',
    title: 'Mount Satima Climb',
    description: 'Challenging climb to the highest point in the Aberdare Range. Stunning views and diverse wildlife.',
    difficulty_level: 'Hard',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.3, lng: 36.7 },
    distance_km: 20,
    elevation_gain_m: 1500,
    duration_hours: 7,
    scheduled_date: getDate(23), // 23 days from today
    start_time: '06:00',
    end_time: '13:00',
    max_capacity: 12,
    available_spots: 7,
    price_kshs: 6000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/satima.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-016',
    title: 'Lake Naivasha Circuit',
    description: 'Moderate walk around Lake Naivasha. Great for bird watching and enjoying the lakeside scenery.',
    difficulty_level: 'Moderate',
    location: 'Naivasha, Kenya',
    coordinates: { lat: -0.7167, lng: 36.4333 },
    distance_km: 14,
    elevation_gain_m: 200,
    duration_hours: 4.5,
    scheduled_date: getDate(25), // 25 days from today
    start_time: '08:00',
    end_time: '12:30',
    max_capacity: 30,
    available_spots: 20,
    price_kshs: 2200,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/naivasha.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-017',
    title: 'Kereita Forest Zipline & Hike',
    description: 'Combination of hiking and ziplining through Kereita Forest. Fun adventure for all ages.',
    difficulty_level: 'Easy',
    location: 'Kiambu, Kenya',
    coordinates: { lat: -1.0, lng: 36.7 },
    distance_km: 5,
    elevation_gain_m: 150,
    duration_hours: 3,
    scheduled_date: getDate(26), // 26 days from today
    start_time: '09:00',
    end_time: '12:00',
    max_capacity: 25,
    available_spots: 19,
    price_kshs: 3500,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/kereita.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'camping-003',
        name: 'Forest Camping',
        description: 'Overnight camping experience in Kereita Forest with guided night walk',
        price_kshs: 4000,
        icon: '⛺',
        available: true,
        requires_booking: true,
        max_participants: 25,
        available_spots: 19
      }
    ],
    is_long_weekend: true,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-018',
    title: 'Mount Kenya Point Lenana',
    description: 'Challenging 4-day trek to Point Lenana, the third highest peak of Mount Kenya. Technical climbing required.',
    difficulty_level: 'Expert',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.1536, lng: 37.2744 },
    distance_km: 55,
    elevation_gain_m: 3200,
    duration_hours: 96,
    scheduled_date: getDate(28), // 28 days from today
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 8,
    available_spots: 1,
    price_kshs: 35000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/lenana.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'camping-004',
        name: 'Base Camp Camping',
        description: 'Extended camping at base camp with professional mountaineering gear',
        price_kshs: 8000,
        icon: '⛺',
        available: true,
        requires_booking: true,
        max_participants: 8,
        available_spots: 1
      }
    ],
    is_long_weekend: true,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-019',
    title: 'Ol Pejeta Conservancy Walk',
    description: 'Easy guided walk through Ol Pejeta Conservancy. See rhinos and other wildlife in their natural habitat.',
    difficulty_level: 'Easy',
    location: 'Laikipia, Kenya',
    coordinates: { lat: 0.0167, lng: 36.9333 },
    distance_km: 6,
    elevation_gain_m: 100,
    duration_hours: 3,
    scheduled_date: getDate(30), // 30 days from today
    start_time: '08:30',
    end_time: '11:30',
    max_capacity: 20,
    available_spots: 15,
    price_kshs: 4000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/ol-pejeta.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-020',
    title: 'Sagana Rapids Adventure',
    description: 'Moderate hike along the Sagana River with opportunities for rock climbing and rappelling.',
    difficulty_level: 'Moderate',
    location: 'Sagana, Kenya',
    coordinates: { lat: -0.6667, lng: 37.2167 },
    distance_km: 11,
    elevation_gain_m: 400,
    duration_hours: 5,
    scheduled_date: getDate(32), // 32 days from today
    start_time: '07:00',
    end_time: '12:00',
    max_capacity: 18,
    available_spots: 11,
    price_kshs: 4200,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/sagana.jpg',
    status: 'Active',
    extra_activities: [
      {
        id: 'golf-003',
        name: 'Golf at Sagana Golf Club',
        description: 'Play a round of golf at the scenic Sagana Golf Club overlooking the river',
        price_kshs: 2800,
        icon: '⛳',
        available: true,
        requires_booking: true,
        max_participants: 4,
        available_spots: 2
      },
      {
        id: 'camping-005',
        name: 'Riverside Camping',
        description: 'Overnight camping by the Sagana River with campfire and stargazing',
        price_kshs: 3000,
        icon: '⛺',
        available: true,
        requires_booking: true,
        max_participants: 18,
        available_spots: 11
      }
    ],
    is_long_weekend: true,
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-021',
    title: 'Mau Forest Nature Trail',
    description: 'Easy to moderate walk through the Mau Forest. Rich biodiversity and beautiful forest scenery.',
    difficulty_level: 'Moderate',
    location: 'Nakuru, Kenya',
    coordinates: { lat: -0.5, lng: 35.9 },
    distance_km: 9,
    elevation_gain_m: 300,
    duration_hours: 3.5,
    scheduled_date: getDate(33), // 33 days from today
    start_time: '08:00',
    end_time: '11:30',
    max_capacity: 22,
    available_spots: 16,
    price_kshs: 2400,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/mau.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-022',
    title: 'Mount Suswa Cave Exploration',
    description: 'Unique moderate hike to explore the caves of Mount Suswa. Fascinating geological formations.',
    difficulty_level: 'Moderate',
    location: 'Narok, Kenya',
    coordinates: { lat: -1.1333, lng: 36.35 },
    distance_km: 12,
    elevation_gain_m: 500,
    duration_hours: 5,
    scheduled_date: getDate(35), // 35 days from today
    start_time: '07:30',
    end_time: '12:30',
    max_capacity: 20,
    available_spots: 13,
    price_kshs: 3800,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/suswa.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-023',
    title: 'Karura Forest Evening Walk',
    description: 'Relaxing evening walk through Karura Forest. Perfect way to end your day in nature.',
    difficulty_level: 'Easy',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2345, lng: 36.7890 },
    distance_km: 4,
    elevation_gain_m: 40,
    duration_hours: 1.5,
    scheduled_date: getDate(35), // Same day as Suswa
    start_time: '17:00',
    end_time: '18:30',
    max_capacity: 30,
    available_spots: 25,
    price_kshs: 800,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/karura-evening.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-024',
    title: 'Aberdare National Park Trek',
    description: 'Hard multi-day trek through Aberdare National Park. Experience diverse wildlife and stunning landscapes.',
    difficulty_level: 'Hard',
    location: 'Nyeri, Kenya',
    coordinates: { lat: -0.35, lng: 36.75 },
    distance_km: 35,
    elevation_gain_m: 2000,
    duration_hours: 48,
    scheduled_date: getDate(37), // 37 days from today
    start_time: '06:00',
    end_time: '18:00',
    max_capacity: 10,
    available_spots: 4,
    price_kshs: 18000,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/aberdare-trek.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
  {
    id: 'trail-025',
    title: 'Ngong Hills Sunset Hike',
    description: 'Moderate evening hike to catch the sunset from Ngong Hills. Breathtaking views of the Rift Valley.',
    difficulty_level: 'Moderate',
    location: 'Ngong, Kenya',
    coordinates: { lat: -1.3456, lng: 36.6543 },
    distance_km: 10,
    elevation_gain_m: 500,
    duration_hours: 3.5,
    scheduled_date: getDate(40), // 40 days from today
    start_time: '16:00',
    end_time: '19:30',
    max_capacity: 25,
    available_spots: 18,
    price_kshs: 2800,
    host: 'Administrator',
    featured_image: '/assets/all_trails/images/ngong-sunset.jpg',
    status: 'Active',
    created_at: '2025-01-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
  },
];

// Mock User Bookings
export const mockBookings: TrailBooking[] = [
  {
    id: 'booking-001',
    user: 'user@example.com',
    trail_id: 'trail-001',
    booking_date: getDate(-5), // 5 days ago
    status: 'Confirmed',
    spots_booked: 2,
    total_price: 30000,
    payment_status: 'Completed',
    confirmation_code: 'CONF-001-ABC',
    created_at: getDate(-5) + 'T10:00:00Z',
    updated_at: getDate(-5) + 'T10:00:00Z',
  },
  {
    id: 'booking-002',
    user: 'user@example.com',
    trail_id: 'trail-003',
    booking_date: getDate(-3), // 3 days ago
    status: 'Confirmed',
    spots_booked: 1,
    total_price: 2500,
    payment_status: 'Completed',
    confirmation_code: 'CONF-002-XYZ',
    created_at: getDate(-3) + 'T10:00:00Z',
    updated_at: getDate(-3) + 'T10:00:00Z',
  },
  {
    id: 'booking-003',
    user: 'user@example.com',
    trail_id: 'trail-005',
    booking_date: getDate(-1), // Yesterday
    status: 'Pending',
    spots_booked: 3,
    total_price: 4500,
    payment_status: 'Pending',
    confirmation_code: 'CONF-003-DEF',
    created_at: getDate(-1) + 'T10:00:00Z',
    updated_at: getDate(-1) + 'T10:00:00Z',
  },
];

// Mock Current User
export const mockCurrentUser: User = {
  name: 'user@example.com',
  email: 'user@example.com',
  full_name: 'John Doe',
  user_image: '/assets/all_trails/images/user-avatar.jpg',
};
